# Generated by Django 3.0.6 on 2020-05-13 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Books',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='post_title',
            new_name='title',
        ),
    ]
